### ISSUE TITLE
full mp3

### ISSUE THREAD

**Issue by dyens** [volchenkov/volchenkov.github.io#1]
Можно ли добавить full версию для words (без разбивки по несколько тактов) ?

Могу сделать пулл реквест, но мои mp3 будут с небольшими сбивками из за обьединения.

**Comment by dyens** [comment]
Создал пулл реквест. Лучше конечно заменить mp3.

**Comment by volchenkov** [comment]
Хорошо, спасибо. Вечером посмотрю. А почему тебе пришлось склеивать? Нет
полной сплошной версии из миди?

вт, 15 янв. 2019 г., 12:38 Alexander notifications@github.com:

**Comment by dyens** [comment]
Не нашел в репе миди ). Мб в группе хора есть..

**Comment by dyens** [comment]
Вообще пора уже создавать репу для хора)

**Comment by volchenkov** [comment]
Да, похоже на то. Уже несколько произведений набрано своих, многие ГТП
делают, повторяясь.
Как думаешь, проще у кого-то в аккаунте проект создать или отдельный
аккаунт зарегистрировать?

ср, 16 янв. 2019 г. в 11:04, Alexander <notifications@github.com>:

**Comment by dyens** [comment]
Правильнее, думаю, отдельный аккаунт. Но проект тоже хорошо - если мэйнтейнер уйдет всегда можно форкнуть)

**Comment by volchenkov** [comment]
Надо создать тогда :) вечером займусь и свой репозиторий перенесу заодно

ср, 16 янв. 2019 г., 11:15 Alexander notifications@github.com:
